database:
  host: 172.16.9.15
  port: 3306
  databasename: gtobusinessdb
  username: root
  password: a111111
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: true
    serviceUrl:
      defaultZone: "http://172.16.9.19:9602/eureka,http://172.16.9.20:9602/eureka,http://172.16.9.21:9602/eureka"
  instance:
    lease-expiration-duration-in-seconds: 40
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
kafka:
  brokers: 172.16.9.11:9092
  zk-nodes: 172.16.9.11:2181
seaweed:
  masterHost: "172.16.9.15:9333"
#zipkin:
#  base-url: http://172.16.9.31:9623  #ZipkinService地址
#  enabled: true
sleuth:
  percentage: 1.0
spring:
  admin: http://172.16.9.31:9625