#database:
#  host: 172.16.9.15
#  port: 3306
#  databasename: gtobusinessdb
#  username: root
#  password: a111111
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: true
    serviceUrl:
      defaultZone: "http://172.16.9.19:9602/eureka,http://172.16.9.20:9602/eureka,http://172.16.9.21:9602/eureka"
  instance:
    lease-expiration-duration-in-seconds: 40
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
kafka:
  brokers: 172.16.9.11:9092
  zk-nodes: 172.16.9.11:2181
seaweed:
  masterHost: "172.16.9.15:9333"
zipkin:
  base-url: http://172.16.9.31:9623  #ZipkinService地址
  enabled: true
sleuth:
  percentage: 0.1
druid:
#  configPathBasic:  /data/appdatas/gt1/gtobasicdb_dev.properties
  configPathBusiness:  /data/appdatas/gt1/gtobusinessdb_dev.properties
#  configPathPayroll:  /data/appdatas/gt1/gtopayrolldb_dev.properties
#  configPathProduct:  /data/appdatas/gt1/gtoproductdb_dev.properties
#  configPathSm:  /data/appdatas/gt1/gtosmdb_dev.properties
#  configPathSupplier:  /data/appdatas/gt1/gtosupplierdb_dev.properties

mongo:
  host: 172.16.9.15 #172.16.9.52 172.16.9.15 172.16.9.16 sit
  port: 27017
  database: payroll_db
  userName: ciicit
  pwd: ciicit!#%