database:
  host: 172.16.9.15
  port: 3306
  databasename: gtobusinessdb
  username: root
  password: a111111
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.24:9602/eureka/,http://172.16.9.25:9602/eureka/"
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 40
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
kafka:
  brokers: 172.16.9.17:9092,172.16.9.18:9092
  zk-nodes: 172.16.9.19:2181,172.16.9.20:2181,172.16.9.21:2181
seaweed:
  masterHost: "172.16.9.15:9333"
zipkin:
  base-url: http://172.16.9.24:9623  #ZipkinService地址
  enabled: true
sleuth:
  percentage: 0.1

mongo:
  host: 172.16.9.16 #172.16.9.52 172.16.9.15 172.16.9.16 sit
  port: 27017
  database: payroll_db
  userName: ciicit
  pwd: ciicit!#%