mybatis-plus:
  mapper-locations: mapper/**.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

spring:
  application:
    name: fcbusinesscenter-payrollslip-slipcommandservice
  datasource:
      url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
      username: ${database.username}
      password: ${database.password}
      driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7015


