eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.56:9602/eureka"
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 40
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}

management:
  security:
   enabled: false

seaweed:
  masterHost: "172.16.9.58:9333"

database:
  host: 172.16.9.53
  port: 3306
  databasename: gtopayrolldb
  username: root
  password: ciicit!#%

kafka:
  brokers: 172.16.9.55:9092
  zk-nodes: 172.16.9.55:2181,172.16.9.56:2181,172.16.9.57:2181

mongo:
  host: 172.16.9.52 #172.16.9.52 172.16.9.15 172.16.9.16 sit
  port: 27017
  database: payroll_db
  userName: ciicit
  pwd: ciicit!#%


