mybatis-plus:
  mapper-locations: mapper/**.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

spring:
  application:
    name: fcbusinesscenter-payrollslip-slipcommandservice
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 7015


