eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.9.24:9602/eureka,http://172.16.9.25:9602/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
mongo:
  host: 172.16.9.16 #172.16.9.52 172.16.9.15 172.16.9.16 sit
  port: 27017
  database: payroll_db
  userName: ciicit
  pwd: ciicit!#%
seaweed:
  masterHost: "172.16.9.19:9333"
spring:
  boot:
    admin:
      api-path: instances
      url: http://172.16.9.24:9625
druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_test.properties
kafka:
  brokers: 172.16.9.17:9092,172.16.9.18:9092
  zk-nodes: 172.16.9.19:2181,172.16.9.20:2181,172.16.9.21:2181