eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.9.24:9602/eureka/
#        defaultZone: http://172.16.9.21:9602/eureka/,http://172.16.9.20:9601/eureka/,http://172.16.9.19:9600/eureka/ #注册中心eureka地址

spring:
  datasource:
    url: jdbc:mysql://172.16.9.15:3306/gtopayrolldb?characterEncoding=utf8&useSSL=true
    username: root
    password: a111111
  application:
    name: fcbusiness-center-command-service
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.9.17:9092,172.16.9.18:9092
          zk-nodes: 172.16.9.19:2181,172.16.9.20:2181,172.16.9.21:2181
          #brokers: 192.168.1.112:9092
          #zk-nodes: 192.168.1.112:2181
          autoAddPartitions: true
          replicationFactor: 2
      bindings:
        payroll-output-channel:
          destination: fc_payroll_batch # topic name
          content-type: application/json
          producer:
            partitionCount: 2

        pr_emp_group-output-channel:
          destination: fc_payroll_empGroup # topic name
          content-type: application/json
          producer:
            partitionCount: 2

        pr_compute-output-channel:
           destination: fc_payroll_compute # topic name
           content-type: application/json
           producer:
             partitionCount: 2

        pr_compute-input-channel:
          destination: fc_payroll_compute-status # topic name
          content-type: application/json
          group: ${spring.application.name} # consumer group
          consumer:
            partitioned: true

logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.ciicsh.zorro.salarymanagementwebservice: DEBUG
    org.mybatis: DEBUG