info:
  app:
    name: 薪资发放
    version: 1.0-SNAPSHOT
    description: 提供服务操作接口
app:
  id: 10007005
endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceurl}
logging:
  file: /tmp/logs/salcenterservice.log
management:
  context-path: /admin
  port: 7010
  #禁用安全验证
  security:
    enabled: false
#pagehelper:
#  reasonable: true
server:
  port: 7009
  session-timeout: "# session timeout in seconds"
  tomcat:
    background-processor-delay: 30
    basedir: /tmp
    max-threads: 0
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: UTF-8
spring:
  application:
    name: fcbusiness-center-salarygrant-site-service
  profiles:
    active: dev
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?useUnicode=true&characterEncoding=utf8&useSSL=true&tinyInt1isBit=false
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.brokers}
          zk-nodes: ${kafka.zk-nodes}
      bindings:
        common-taskservice-sal-agreement-audit-channel:
          destination: common_taskservice_sal_agreement_audit # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
        common-taskservice-sal-cust-qualify-audit:
          destination: common_taskservice_sal_cust_qualify_audit # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
        common-taskservice-sal-new-project-audit:
          destination: common_taskservice_sal_new_project_audit # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
        common-taskservice-sale-manager-audit:
          destination: common_taskservice_sale_manager_audit # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
        common-taskservice-sale-seal-audit:
          destination: common_taskservice_sale_seal_audit # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
        common-taskservice-process-complete:
          destination: common_taskservice_process_complete # topic name
          group: sale-center-site-service
          content-type: application/json
          consumer:
            partitioned: true
      instance-count: 2
      instance-index: 0
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #驼峰下划线转换
    db-column-underline: true
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  mapper-locations: mapper/*Mapper.xml
seaweed:
  masterHost: ${seaweed.masterHost}