spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: ${database.username}
    password: ${database.password}
  application:
    name: fcbusiness-center-salary-compute
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.brokers}
          zk-nodes: ${kafka.zk-nodes}
          autoAddPartitions: true

      bindings:
        pr_compute-input-channel:
          destination: fc_payroll_compute_result # 薪资计算 topic
          content-type: application/json
          group: compute_async # consumer group
          consumer:
            partitioned: true

        pr_compute-status-output-channel:
          destination: fc_payroll_compute-status # topic name
          content-type: application/json
          producer:
            partitionCount: 1
  profiles:
    active: test

      #instance-count: 2
      #instance-index: 1
server:
  port: 7034


app:
  id: 10007022
  name: SalaryComputeJob

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.salarymanagement.entity.po

  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      cache-enabled: false