spring:
  application:
    name: fcbusiness-center-salary-compute
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.brokers}
          zk-nodes: ${kafka.zk-nodes}
          autoAddPartitions: true

      bindings:
        pr_compute-input-channel:
          destination: fc_payroll_compute_result # 薪资计算 topic
          content-type: application/json
          group: gt1_compute_temp # consumer group
          consumer:
            partitioned: true
            #resetOffsets: true
            #startOffset: latest

        pr_compute-status-output-channel:
          destination: fc_payroll_compute-status # topic name
          content-type: application/json
          producer:
            partitionCount: 1
  profiles:
    active: dev

      #instance-count: 2
      #instance-index: 1
server:
  port: 7034

app:
  id: 10007022
  name: SalaryComputeJob

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.salarymanagement.entity.po

  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      cache-enabled: false