eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.56:9602/eureka"

management:
  security:
   enabled: false

seaweed:
  masterHost: "172.16.22.110:9333"

kafka:
  brokers: 172.16.100.101:9092
  zk-nodes: 172.16.100.101:2181,172.16.100.102:2181,172.16.100.109:2181

mongo:
  host: 172.16.22.113  # 172.16.9.52 java -Xms384m -Xmx512m -jar app.jar --spring.profiles.active=qa --server.port=8060
  port: 27017
  database: payroll_db
  userName: ciicit
  pwd: ciicit!#%

druid:
   configPath:  /data/appdatas/gt1/gtopayrolldb_prd.properties