eureka:
    client:
        service-url:
            defaultZone: http://172.16.9.21:9602/eureka
log4j:
    logger:
        Java:
            sql:
                Connection: DEBUG
        com:
            ibatis: DEBUG
            ibatis.common.jdbc.ScriptRunner: DEBUG
            ibatis.common.jdbc.SimpleDataSource: DEBUG
            ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
        java:
            sql:
                PreparedStatement: DEBUG
                Statement: DEBUG
logging:
    config: classpath:config/logback-spring.xml
mybatis-plus:
    configuration:
        cache-enabled: false
        map-underscore-to-camel-case: true
    global-config:
        db-column-underline: true
        field-strategy: 2
        id-type: 0
        logic-delete-value: 0
        logic-not-delete-value: 1
    mapper-locations: classpath*:mapper/*.xml
pagehelper:
    reasonable: true

server:
    port: 9001
    session-timeout: '# session timeout in seconds'
    tomcat:
        background-processor-delay: 30.0
        basedir: '/tmp '
        max-threads: 0.0
        protocol-header: 'x-forwarded-proto '
        remote-ip-header: x-forwarded-for
spring:
    application:
        name: fc-support-center-query-service-tax
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 10
        max-active: 20
        max-idle: 8
        min-idle: 8
        password: a111111
        url: jdbc:mysql://172.16.9.15:3306/gtobusinessdb?characterEncoding=utf8&useSSL=false
        username: root
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true
