app:
  id : 10007010
  name: TaxCommandService
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.9.56:9602/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#log4j:
#    rootLogger: DEBUG, Console
#    appender:
#        Console: org.apache.log4j.ConsoleAppender
#        Console.layout: org.apache.log4j.PatternLayout
##        Console.layout.ConversionPattern: %d [%t] %-5p [%c] - %m%n
#    logger:
#        Java:
#            sql:
#                Connection: DEBUG
#        com:
#            ibatis: DEBUG
#            ibatis.common.jdbc.ScriptRunner: DEBUG
#            ibatis.common.jdbc.SimpleDataSource: DEBUG
#            ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
#        java:
#            sql:
#                PreparedStatement: DEBUG
#                Statement: DEBUG
#logging:
#    config: classpath:config/logback-spring.xml
logging:
    level:
        org.springframework.web: DEBUG
        org.mybatis: DEBUG
        com.ciicsh.gto.fcbusinesscenter.tax.commandservice.dao: DEBUG
        com.ciicsh.gto.fcbusinesscenter.tax.commandservice.host.controller: DEBUG
        com.ciicsh.gto.fcbusinesscenter.tax.commandservice.business.impl: DEBUG
    pattern:
        console: "[%-5p] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: D:/logs/mylog.log
mybatis-plus:
    configuration:
        cache-enabled: false
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    global-config:
        db-column-underline: true
        field-strategy: 2
        id-type: 0
        logic-delete-value: 0
        logic-not-delete-value: 1
        meta-object-handler: com.ciicsh.gto.fcbusinesscenter.tax.commandservice.host.handler.TaxMetaObjectHandler
    mapper-locations: classpath*:mapper/*.xml
#    config-location: classpath:mybatis-config.xml
pagehelper:
    reasonable: true

server:
    port: 7019
#    context-path: /tax
    session-timeout: '# session timeout in seconds'
    tomcat:
        background-processor-delay: 30.0
        basedir: '/tmp '
        max-threads: 0.0
        protocol-header: 'x-forwarded-proto '
        remote-ip-header: x-forwarded-for
spring:
    application:
        name: fcbusiness-center-tax-command-service
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        show-sql: true
    cloud:
      stream:
        kafka:
          binder:
            brokers: 172.16.9.55:9092
            zk-nodes: 172.16.9.55:2181,172.16.9.56:2181,172.16.9.57:2181
            autoAddPartitions: true
            replicationFactor: 2
        bindings:
          pay-apply-pay-status-stream:
            destination: pay_apply_pay_status_stream
            content-type: application/json
            group: ${spring.application.name}
            consumer:
              partitioned: false
          pr-compute-close-output-channel:
            destination: fc_compute_close
            content-type: application/json
            group: ${spring.application.name}
            consumer:
              partitioned: false
          pr-compute-unclose-output-channel:
            destination: fc_compute_unclose
            content-type: application/json
            group: ${spring.application.name}
            consumer:
              partitioned: false
          common-taskservice-fc-tax-main-task-audit:
            destination: common_taskservice_fc_tax_main_task_audit
            content-type: application/json
            group: ${spring.application.name}
            consumer:
              partitioned: false
          common-taskservice-process-complete:
            destination: common_taskservice_process_complete
            content-type: application/json
            group: ${spring.application.name}
            consumer:
              partitioned: false
    data:
      mongodb:
        uri: mongodb://ciicit:ciicit!%23%25@172.16.9.15:27017/payroll_db
    zipkin:
      base-url: http://172.16.9.56:9623 #ZipkinService地址
      enabled: true
    sleuth:
      sampler:
        percentage: 0.1
    boot:
      admin:
        url: http://172.16.9.56:9625
druid:
    configPath:  /data/appdatas/gt1/gtobusinessdb_uat.properties
