mybatis:
  mapperLocations: classpath:mapper/*.xml
#  config-location: classpath:/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ciicsh.zorro.leopardwebservice.entity

spring:
  datasource:
    url: jdbc:mysql://172.16.9.15:3306/gtopayrolldb?characterEncoding=utf8&useSSL=true
    username: root
    password: a111111
    driver-class-name: com.mysql.jdbc.Driver
