
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: ${database.username}
    password: ${database.password}
  application:
    name: fcbusiness-center-compute-task
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka.brokers}
          zk-nodes: ${kafka.zk-nodes}
          autoAddPartitions: true
      bindings:
        pr-normal-batch-input-channel:
          destination: fc_payroll_normal_batch # 正常批次新增或者删除
          content-type: application/json
          group: ${spring.application.name} # consumer group
          consumer:
            partitioned: true

        pr_emp_group-channel:
          destination: fc_payroll_empGroup # 雇员组的雇员变化
          content-type: application/json
          group: ${spring.application.name} # consumer group
          consumer:
            partitioned: true

        pr_adjust_batch-input-channel:
          destination: fc_payroll_adjust_batch # 调整批次
          content-type: application/json
          group: ${spring.application.name} # consumer group
          consumer:
            partitioned: true

        pr_compute-complete-input-channel:
          destination: fc_payroll_compute-complete # 计算完成，审核通过，批次自动关帐
          content-type: application/json
          group: ${spring.application.name} # consumer group
          consumer:
            partitioned: true

  profiles:
    active: dev

      #instance-count: 2
      #instance-index: 1
server:
  port: 7033

app:
  id: 10007023
  name: CalDispatchJob

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.salarymanagement.entity.po

  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      cache-enabled: false